### ISSUE TITLE
Implement an automated test to detect merge commits

### ISSUE THREAD

**Issue by mbestavros** [enarx/sevctl#11]
Enarx projects should not contain merge commits, and we'd like to test incoming pull requests to ensure they do not contain any.

The best way to go about this is probably to detect whether individual commits have multiple parents. There is no simple one-line way to do this, so we'll need to implement it from scratch (probably by iterating through PR commits and analyzing them).

**Comment by connorkuehl** [comment]
@mbestavros Did you still want to track this? I'm moving issues to the main enarx/enarx repo since that's where `sevctl` lives now.

**Comment by mbestavros** [comment]
@connorkuehl There's already an issue for it: https://github.com/enarx/enarx/issues/51

**Comment by connorkuehl** [comment]
Ah, okay! Thanks!
